SELECT  b.FEATURE_ID AS "Id" ,
        a.FEATURE_NAME AS "Name"
FROM    TB_M_FEATURE a
        INNER JOIN TB_M_ROLE_FEATURE b ON b.FEATURE_ID = a.FEATURE_ID
WHERE b.ROLE_ID = @RoleId
AND b.FUNCTION_ID = @FunctionId