update tb_m_user set [REG_NO] = @RegistrationNumber
					,[COMPANY_CODE] = @CompanyCode
					,[PASSWORD] = @Password 						
				    ,[PASSWORD_EXPIRATION_DATE] = @PasswordExpirationDate
				    ,[ACCOUNT_VALIDITY_DATE] = @AccountValidityDate
				    ,[FIRST_NAME] = @FirstName
				    ,[LAST_NAME] = @LastName
				    ,[PHONE_NO] = @PhoneNumber
				    ,[EXT_NO] = @ExtensionNumber
				    ,[MOBILE_NO] = @MobileNumber
				    ,[EMAIL] = @Email
				    ,[CLASS_ID] = @ClassId
				    ,[JOB_FUNCTION] = @JobFunction
				    ,[CC_CODE] = @CCCode
				    ,[LOCATION_ID] = @LocationId
				    ,[MAX_LOGON] = @MaxLogon
				    ,[DEFAULT_SYSTEM] = @DefaultSystem
				    ,[PRODUCTION_FLAG] = @ProductionFlag
				    ,[ACTIVE_DIRECTORY_FLAG] = @ActiveDirectoryFlag
				    ,[CHANGED_BY] = 'system'
				    ,[CHANGED_DATE] = GETDATE()
				    ,[SHIFT] = @Shift
				    ,[ACTIVE_FLAG] = @ActiveFlag
where username = @Username