INSERT INTO [TB_M_USER]
           ([USERNAME]
           ,[REG_NO]
           ,[COMPANY_CODE]
           ,[PASSWORD]
           ,[PASSWORD_EXPIRATION_DATE]
           ,[ACCOUNT_VALIDITY_DATE]
           ,[FIRST_NAME]
           ,[LAST_NAME]
           ,[PHONE_NO]
           ,[EXT_NO]
           ,[MOBILE_NO]
           ,[EMAIL]
           ,[CLASS_ID]
           ,[JOB_FUNCTION]
           ,[CC_CODE]
           ,[LOCATION_ID]
           ,[MAX_LOGON]
           ,[DEFAULT_SYSTEM]
           ,[PRODUCTION_FLAG]
           ,[ACTIVE_DIRECTORY_FLAG]
           ,[CREATED_BY]
           ,[CREATED_DATE]
           ,[SHIFT]
           ,[ACTIVE_FLAG]
		   ,[LOCK_FLAG]
		   ,[NOTIFICATION_FLAG]
		   ,[DELETED_FLAG])
     VALUES
           (@Username
           ,@RegistrationNumber
           ,@CompanyCode
           ,@Password
           ,@PasswordExpirationDate
           ,@AccountValidityDate
           ,@FirstName
           ,@LastName
           ,@PhoneNumber
           ,@ExtensionNumber
           ,@MobileNumber
           ,@Email
           ,@ClassId
           ,@JobFunction
           ,@CCCode
           ,@LocationId
           ,@MaxLogon
           ,@DefaultSystem
           ,@ProductionFlag
           ,@ActiveDirectoryFlag
           ,'system'
           ,GETDATE()
           ,@Shift
           ,@ActiveFlag
		   ,0
		   ,0
		   ,0)