/****** Database Logging Sink Table Structure ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_R_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SESSION] [varchar](50) NOT NULL,
	[SEVERITY] [tinyint] NOT NULL,
	[MESSAGE] [text] NULL,
 CONSTRAINT [PK_TB_R_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO