INSERT INTO TB_R_BACKGROUND_TASK_REGISTRY
           ([ID]
           ,[NAME]
           ,[DESCRIPTION]
           ,[SUBMITTER]
           ,[FUNCTION_NAME]
           ,[PARAMETER]
           ,[TYPE]
           ,[STATUS]
		   ,[COMMAND]
		   ,[START_DATE]
           ,[END_DATE]
           ,[PERIODIC_TYPE]
           ,[INTERVAL]
		   ,[TIME]
           ,[EXECUTION_DAYS]
           ,[EXECUTION_MONTHS])
     VALUES
           (@Id
           ,@Name
           ,@Description
           ,@Submitter
           ,@FunctionName
           ,@Parameter
           ,@Type
           ,@Status
		   ,@Command
		   ,@StartDate
		   ,@EndDate
		   ,@PeriodicType
		   ,@Interval
		   ,@Time
		   ,@ExecutionDays
		   ,@ExecutionMonths)