IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_R_BACKGROUND_TASK_REGISTRY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TB_R_BACKGROUND_TASK_REGISTRY](
	[ID] [varchar](100) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
	[SUBMITTER] [varchar](50) NOT NULL,
	[FUNCTION_NAME] [varchar](50) NOT NULL,
	[PARAMETER] [varchar](255) NULL,
	[TYPE] [tinyint] NOT NULL,
	[STATUS] [tinyint] NOT NULL,
	[COMMAND] [varchar](255) NOT NULL,
	[START_DATE] [bigint] NOT NULL,
	[END_DATE] [bigint] NOT NULL,
	[PERIODIC_TYPE] [tinyint] NOT NULL,
	[INTERVAL] [tinyint] NULL,
	[TIME] [bigint] NOT NULL,
	[EXECUTION_DAYS] [varchar](50) NOT NULL,
	[EXECUTION_MONTHS] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TB_R_BACKGROUND_TASK_REGISTRY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TB_R_BACKGROUND_TASK_REGISTRY]') AND name = N'IX_TB_R_BACKGROUND_TASK_REGISTRY')
CREATE NONCLUSTERED INDEX [IX_TB_R_BACKGROUND_TASK_REGISTRY] ON [dbo].[TB_R_BACKGROUND_TASK_REGISTRY] 
(
	[ID] ASC,
	[FUNCTION_NAME] ASC,
	[TYPE] ASC,
	[NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_R_BACKGROUND_TASK_QUEUE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TB_R_BACKGROUND_TASK_QUEUE](
	[ID] [varchar](100) NOT NULL,
	[REGISTRY_ID] [varchar](100) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
	[SUBMITTER] [varchar](50) NOT NULL,
	[FUNCTION_NAME] [varchar](50) NOT NULL,
	[PARAMETER] [varchar](255) NULL,
	[TYPE] [tinyint] NOT NULL,
	[STATUS] [tinyint] NOT NULL,
	[COMMAND] [varchar](255) NOT NULL,
	[START_DATE] [bigint] NULL,
	[END_DATE] [bigint] NULL,
	[PERIODIC_TYPE] [tinyint] NULL,
	[INTERVAL] [tinyint] NULL,
	[TIME] [bigint] NULL,
	[EXECUTION_DAYS] [varchar](50) NULL,
	[EXECUTION_MONTHS] [varchar](50) NULL,
	[START_TIME] [datetime] NULL,
	[FINISH_TIME] [datetime] NULL,
	[PROGRESS] [tinyint] NULL,
 CONSTRAINT [PK_TB_R_BACKGROUND_TASK_QUEUE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[REGISTRY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TB_R_BACKGROUND_TASK_QUEUE]') AND name = N'IX_TB_R_BACKGROUND_TASK_QUEUE')
CREATE NONCLUSTERED INDEX [IX_TB_R_BACKGROUND_TASK_QUEUE] ON [dbo].[TB_R_BACKGROUND_TASK_QUEUE] 
(
	[ID] ASC,
	[FUNCTION_NAME] ASC,
	[TYPE] ASC,
	[NAME] ASC,
	[STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_R_BACKGROUND_TASK_HISTORY]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TB_R_BACKGROUND_TASK_HISTORY](
	[ID] [varchar](100) NOT NULL,
	[REGISTRY_ID] [varchar](100) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
	[SUBMITTER] [varchar](50) NOT NULL,
	[FUNCTION_NAME] [varchar](50) NOT NULL,
	[PARAMETER] [varchar](255) NULL,
	[TYPE] [tinyint] NOT NULL,
	[STATUS] [tinyint] NOT NULL,
	[COMMAND] [varchar](255) NOT NULL,
	[START_DATE] [bigint] NULL,
	[END_DATE] [bigint] NULL,
	[PERIODIC_TYPE] [tinyint] NULL,
	[INTERVAL] [tinyint] NULL,
	[TIME] [bigint] NULL,
	[EXECUTION_DAYS] [varchar](50) NULL,
	[EXECUTION_MONTHS] [varchar](50) NULL,
	[START_TIME] [datetime] NULL,
	[FINISH_TIME] [datetime] NULL,
	[PROGRESS] [tinyint] NULL,
 CONSTRAINT [PK_TB_R_BACKGROUND_TASK_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[REGISTRY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TB_R_BACKGROUND_TASK_HISTORY]') AND name = N'IX_TB_R_BACKGROUND_TASK_HISTORY')
CREATE NONCLUSTERED INDEX [IX_TB_R_BACKGROUND_TASK_HISTORY] ON [dbo].[TB_R_BACKGROUND_TASK_HISTORY] 
(
	[ID] ASC,
	[FUNCTION_NAME] ASC,
	[NAME] ASC,
	[TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

